var res = {
  akarui: "res/akarui.mp3",
  sitatoge: "res/下とげ.png",
  yokotoge: "res/横とげ.png",
    onp: "res/onp.png",
    onp2: "res/onp2.png",
    reset: "res/reset.png",
    haikeimori: "res/よくない.jpg",
    kazan: "res/火山.jpg",
    koujou: "res/工場.jpg",
    mori: "res/mori.mp3",
    yukibgm: "res/yuki.mp3",
    koujoubgm: "res/koujou.mp3",
    kazan2: "res/kazan2.mp3",
    eyeshine1: "res/eye-shine1.mp3",
    gameover: "res/opsakebi.mp3",
    titlehaikei: "res/titlehaikei.png",
    titlegazou: "res/title.png",
    menu: "res/menu.png",
    kumo: "res/kumo.png",
    winkao1: "res/winkao1.png",
    winkao2: "res/winkao2.png",
    winkao3: "res/winkao3.png",
    winkao4: "res/winkao4.png",
    winkao5: "res/winkao5.png",
    winkao6: "res/winkao6.png",
    losekao1: "res/losekao1.png",
    hutuunoki: "res/hutuunoki.png",
    kusattaki: "res/kusattaki.png",
    midoriteki: "res/midoriteki1.png",
    akateki: "res/akateki1.png",
    aoteki: "res/aoteki1.png",
    haiteki: "res/haiteki1.png",
    brick2x1_png: "res/brick2x1.png",
    brick3x1_png: "res/brick3x1.png",
    brick4x1_png: "res/brick4x1.png",
    brick4x2_png: "res/brick4x2.png",
    ground_png: "res/ground.png",
    kusa: "res/kusa.png",
    kusatate: "res/kusatate.png",
    sunakusa: "res/sunakusa.png",
    iceground: "res/iceground.png",
    icegroundwall: "res/icegroundwall.png",
    totem_png: "res/player1.png",
    landing_mp3: "res/landing.mp3",
    yukiyama: "res/yukiyama.png",
    kuritonneru: "res/クリスタルとんねる.jpg",
    haikeikusa: "res/素晴らしいと思う.jpg",
    kikaiyuka: "res/kikaiyuka.png",
    kikaiyuka2: "res/機械床.png",
    kikaiyuka3: "res/機械床横.png",
    berutokonbea: "res/berutokonbea.png",
    erebeta: "res/erebeta.png",
    kooriyuka: "res/kooriyuka.png",
    kooriyukatate: "res/kooriyukatate.png",
    sayuuerebeta: "res/sayuuerebeta.png",
    medamayaki: "res/medamayaki.png",
    stagebgm1: "res/stagebgm.mp3",
    maguma: "res/maguma.png",
    magumayuka: "res/magumayuka.png",
    magumakabe: "res/magumakabe.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
